[comics]
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

listen.owner = www-data
listen.group = www-data
listen = /run/php/php8.3-fpm-comics.sock

user = www-data
group = www-data


php_admin_value[error_log] = /var/log/php/comics.log
